-- ============================================
-- LOVDATA METADATA TABLE (COMPLETE)
-- For use with Supabase Database
-- ============================================

CREATE TABLE IF NOT EXISTS lovdata_metadata (
  -- Primary key
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  -- Essential file information
  file_name TEXT NOT NULL UNIQUE,         -- Example: nl-20190301-0002.xml
  file_hash TEXT NOT NULL,                -- MD5 hash for deduplication
  file_size BIGINT,                       -- File size in bytes
  
  -- Supabase Storage specific fields
  storage_bucket TEXT,                    -- Bucket name (e.g., 'lovdata-docs')
  storage_path TEXT,                      -- Path within bucket (e.g., '01_Laws_and_Regulations/Active_Laws_NL/nl-20051221-0123.xml')
  public_url TEXT,                        -- Public URL for file access
  
  -- Legacy field for compatibility
  file_storage_uri TEXT NOT NULL,         -- Full URI (e.g., supabase://lovdata-docs/Category/file.xml)
  
  -- Document classification
  category TEXT NOT NULL,                 -- Main category: 01_Laws_and_Regulations
  subcategory TEXT,                       -- Subcategory: Active_Laws_NL
  
  -- Source tracking
  source_url TEXT NOT NULL,               -- Original Lovdata URL
  
  -- Content preview (500 characters for search/Excel)
  content_preview TEXT,                   -- First 500 chars of content
  
  -- Additional metadata (JSON)
  metadata JSONB                          -- Additional metadata as JSON
);

-- -- ============================================
-- -- INDEXES for faster queries
-- -- ============================================
-- CREATE INDEX IF NOT EXISTS idx_file_name ON lovdata_metadata(file_name);
-- CREATE INDEX IF NOT EXISTS idx_file_hash ON lovdata_metadata(file_hash);
-- CREATE INDEX IF NOT EXISTS idx_category ON lovdata_metadata(category);
-- CREATE INDEX IF NOT EXISTS idx_subcategory ON lovdata_metadata(subcategory);
-- CREATE INDEX IF NOT EXISTS idx_created_at ON lovdata_metadata(created_at DESC);
-- CREATE INDEX IF NOT EXISTS idx_source_url ON lovdata_metadata(source_url);
-- CREATE INDEX IF NOT EXISTS idx_storage_path ON lovdata_metadata(storage_path);

-- -- Create index on metadata JSON field for faster searches
-- CREATE INDEX IF NOT EXISTS idx_metadata ON lovdata_metadata USING GIN(metadata);

-- -- Full-text search on content preview (Norwegian language)
-- CREATE INDEX IF NOT EXISTS idx_content_preview ON lovdata_metadata 
-- USING GIN(to_tsvector('norwegian', content_preview));

-- -- ============================================
-- -- TRIGGERS
-- -- ============================================

-- -- Auto-update updated_at timestamp
-- CREATE OR REPLACE FUNCTION update_updated_at_column()
-- RETURNS TRIGGER AS $$
-- BEGIN
--     NEW.updated_at = now();
--     RETURN NEW;
-- END;
-- $$ language 'plpgsql';

-- CREATE TRIGGER update_lovdata_metadata_updated_at 
-- BEFORE UPDATE ON lovdata_metadata 
-- FOR EACH ROW
-- EXECUTE PROCEDURE update_updated_at_column();

-- -- ============================================
-- -- USEFUL VIEWS
-- -- ============================================

-- -- View: Documents by category
-- CREATE OR REPLACE VIEW documents_by_category AS
-- SELECT 
--   category,
--   subcategory,
--   COUNT(*) as total_documents,
--   SUM(file_size) / 1024 / 1024 as total_size_mb,
--   MIN(created_at) as first_scraped,
--   MAX(created_at) as last_scraped
-- FROM lovdata_metadata
-- GROUP BY category, subcategory
-- ORDER BY category, subcategory;

-- -- View: Recent documents
-- CREATE OR REPLACE VIEW recent_documents AS
-- SELECT 
--   file_name,
--   category,
--   subcategory,
--   source_url,
--   public_url,
--   file_size / 1024 as size_kb,
--   created_at
-- FROM lovdata_metadata
-- ORDER BY created_at DESC
-- LIMIT 100;

-- -- ============================================
-- -- USEFUL FUNCTIONS
-- -- ============================================

-- -- Function: Get document count by category
-- CREATE OR REPLACE FUNCTION get_category_stats(category_name TEXT)
-- RETURNS TABLE (
--   subcategory TEXT,
--   count BIGINT,
--   total_size_mb NUMERIC
-- ) AS $$
-- BEGIN
--   RETURN QUERY
--   SELECT 
--     l.subcategory,
--     COUNT(*) as count,
--     ROUND(SUM(l.file_size)::NUMERIC / 1024 / 1024, 2) as total_size_mb
--   FROM lovdata_metadata l
--   WHERE l.category = category_name
--   GROUP BY l.subcategory
--   ORDER BY count DESC;
-- END;
-- $$ LANGUAGE plpgsql;

-- -- Function: Search documents
-- CREATE OR REPLACE FUNCTION search_documents(search_term TEXT)
-- RETURNS TABLE (
--   file_name TEXT,
--   category TEXT,
--   subcategory TEXT,
--   source_url TEXT,
--   public_url TEXT,
--   relevance REAL
-- ) AS $$
-- BEGIN
--   RETURN QUERY
--   SELECT 
--     l.file_name,
--     l.category,
--     l.subcategory,
--     l.source_url,
--     l.public_url,
--     ts_rank(to_tsvector('norwegian', l.content_preview), plainto_tsquery('norwegian', search_term)) as relevance
--   FROM lovdata_metadata l
--   WHERE to_tsvector('norwegian', l.content_preview) @@ plainto_tsquery('norwegian', search_term)
--   ORDER BY relevance DESC
--   LIMIT 50;
-- END;
-- $$ LANGUAGE plpgsql;

-- -- ============================================
-- -- SAMPLE QUERIES
-- -- ============================================

-- /*
-- -- Count documents by category
-- SELECT * FROM documents_by_category;

-- -- Recent documents
-- SELECT * FROM recent_documents LIMIT 20;

-- -- Get stats for specific category
-- SELECT * FROM get_category_stats('01_Laws_and_Regulations');

-- -- Search for documents containing "arbeidsgiver"
-- SELECT * FROM search_documents('arbeidsgiver');

-- -- Total storage usage
-- SELECT 
--   COUNT(*) as total_files,
--   SUM(file_size) / 1024 / 1024 as total_mb,
--   AVG(file_size) / 1024 as avg_kb
-- FROM lovdata_metadata;

-- -- Find duplicates by hash
-- SELECT 
--   file_hash,
--   COUNT(*) as duplicate_count,
--   array_agg(file_name) as files
-- FROM lovdata_metadata
-- GROUP BY file_hash
-- HAVING COUNT(*) > 1;

-- -- Documents per category
-- SELECT 
--   category,
--   COUNT(*) as count,
--   SUM(file_size) / 1024 / 1024 as total_mb
-- FROM lovdata_metadata
-- GROUP BY category
-- ORDER BY count DESC;
-- */

-- -- ============================================
-- -- NOTES
-- -- ============================================
-- -- 
-- -- This schema supports:
-- -- 1. Supabase Storage integration
-- -- 2. Full-text search on content
-- -- 3. Advanced statistics and tracking
-- -- 4. JSON metadata for flexibility
-- -- 5. Automatic timestamp updates
-- --
-- -- The storage_path field stores the path for Supabase Storage API
-- -- The content_preview field stores first 500 chars for search and Excel export
